---
- name: Resource group operations on PowerFlex array.
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    hostname: 'x.x.x.x'
    username: 'admin'
    password: 'Password'
    validate_certs: false
    host_port: 443

  tasks:
    - name: Validate deployment of a resource group
      register: result
      dellemc.powerflex.resource_group:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        resource_group_name: ans_rg
        description: ans_rg
        template_id: "c65d0172-8666-48ab-935e-9a0bf69ed66d"
        firmware_repository_name: "PowerFlex 4.5.0.0"
        validate: true

    - name: Deploy a resource group
      register: result
      dellemc.powerflex.resource_group:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        resource_group_name: ans_rg
        description: ans_rg
        template_id: "c65d0172-8666-48ab-935e-9a0bf69ed66d"
        firmware_repository_name: "PowerFlex 4.5.0.0"

    - name: Delete a resource group
      register: result
      dellemc.powerflex.resource_group:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        resource_group_name: ans_rg
        state: "absent"
