---
- name: Gatherfacts Module Operations on PowerFlex
  hosts: localhost
  connection: local
  tasks:
    - name: Get configured MDM IP addresses
      dellemc.powerflex.mdm_cluster:
        hostname: 10.247.100.223
        # hostname: 10.247.101.69
        username: 'admin'
        password: 'Password123'
        validate_certs: false
        state: "present"
      register: powerflex_sdc_result
      delegate_to: "{{ lookup('ansible.builtin.env', 'RUNON', default='localhost') }}"

    - name: Set fact - count
      ansible.builtin.set_fact:
        powerflex_mdm_slaves_count: "{{ powerflex_sdc_result.mdm_cluster_details.slaves | length }}"
        powerflex_mdm_tb_count: "{{ powerflex_sdc_result.mdm_cluster_details.tieBreakers | length }}"

    - name: Set fact - count
      ansible.builtin.set_fact:
        powerflex_mdm_secondary_id: "{{ powerflex_sdc_result.mdm_cluster_details.slaves[0].id}}"
        powerflex_tb_primary_id: "{{ powerflex_sdc_result.mdm_cluster_details.tieBreakers[0].id}}"
      when: "{{powerflex_mdm_slaves_count}} > 0"

    - name: Set fact - count
      ansible.builtin.set_fact:
        powerflex_mdm_teritery_id: "{{ powerflex_sdc_result.mdm_cluster_details.slaves[1].id}}"
        powerflex_tb_secondary_id: "{{ powerflex_sdc_result.mdm_cluster_details.tieBreakers[1].id}}"
      when: "{{powerflex_mdm_slaves_count}} > 1"

    - name: Print 3 nodes
      debug: 
        msg: '{{ powerflex_mdm_secondary_id }} and {{ powerflex_tb_primary_id }}'
    
    - name: Print 5 nodes
      debug: 
        msg: '{{ powerflex_mdm_teritery_id }} and {{ powerflex_tb_secondary_id }}'
